### ISSUE TITLE
How do you make multiple tenants or landlord?

### ISSUE THREAD

**Issue by ThinkDevStudios** [torzer/awesome-landlord#11]
Hi! Let say i have users who are linked to a shop. Users can make shops and other data like customers and etc are linked via the shop model.

Do I need to add multiple tenants?
`LandLord::addTenant($request->user());`
users should still be able to create shops but can only view created shops
`LandLord::addTenant($request->shop());`

**Comment by nunomazer** [comment]
hi, if I understood you have two situations:

1) Users do shopping in one Shop Store: this kind of relation do not configured a tenant relationship, but a customer <-> shopping

2) User can create a new Shop Store and owned it, this situations is a tenant relationship. The problem is if you allow user to have multiple Shop Stores, so, I would ask first wich one he/she will work on and then set the tenant for an administrative area related to that specific store.

**Comment by ThinkDevStudios** [comment]
Hi. For those who have multiple shop stores. They can access their shop data individually. They need to click the specific shop first and it will be stored in the session as the currently selected shop.

**Comment by nunomazer** [comment]
Ok, so, did you solve this question?
